name: "Decidim: Setup app"
description: Decidim module setup (test app generation)
author: mainio
inputs:
  use-cached-app:
    description: Adds the generated test application to the cache.
    required: false
    default: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 1
    - uses: mainio/gha-decidim-module/app-cache@main
      id: decidim-app-cache
      if: ${{ fromJSON(inputs.use-cached-app) }}
    - uses: mainio/gha-decidim-module/create-app@main
      if: ${{ steps.decidim-app-cache.outputs.cache-hit != 'true' }}
