name: "Decidim: Setup app"
description: Decidim module setup (test app generation)
author: mainio
inputs:
  use-cached-app:
    description: Adds the generated test application to the cache.
    required: false
    default: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        rubygems: latest
    - run: (test -f package-lock.json && echo "available=true" || echo "available=false") >> $GITHUB_OUTPUT
      id: decidim-app-package-lock-availability
      name: Check for package-lock.json
      shell: "bash"
    - uses: actions/setup-node@v3
      with:
        cache: npm
        cache-dependency-path: ./package-lock.json
      if: ${{ fromJSON(steps.decidim-app-package-lock-availability.outputs.available) }}
    - uses: actions/cache@v3
      id: decidim-app-cache
      with:
        path: ./spec/decidim_dummy_app/
        key: decidim-app-${{ github.sha }}
        restore-keys: decidim-app-${{ github.sha }}
      if: ${{ fromJSON(inputs.use-cached-app) }}
    - run: bundle exec rake test_app
      name: Create test app
      shell: "bash"
    - run: mkdir -p ./spec/decidim_dummy_app/tmp/screenshots
      name: Create the screenshots folder
      shell: "bash"
    - run: |
        node -e "
          const fs = require('fs');
          const pkg = JSON.parse(fs.readFileSync('package.json'));
          pkg.overrides = Object.assign(pkg.overrides || {}, { graphql: '15.10.1' });
          fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2));
        "
        rm -rf node_modules package-lock.json
        npm install
      working-directory: ./spec/decidim_dummy_app
      name: Lock graphql to version 15
      shell: "bash"
    - run: RAILS_ENV=test bundle exec rails assets:precompile
      name: Precompile assets
      working-directory: ./spec/decidim_dummy_app/
      shell: "bash"
