on: workflow_call
jobs:
  build_app:
    name: Build app
    runs-on: ubuntu-latest
    if: "!startsWith(github.head_ref, 'chore/l10n')"
    timeout-minutes: 60
    env:
      RUBYOPT: '-W:no-deprecated'
      DISABLE_SPRING: "true"
      POSTGRES_VERSION: 14
    steps:
      - uses: mainio/gha-decidim-module/setup-app@next
